version: '3'

services:
  verbecc:
    container_name: verbecc
    image: bretttolbert/verbecc-svc:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network
    expose:
      - '8000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  api:
    depends_on:
      - verbecc
    container_name: api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - app_network
    expose:
      - '4000'
    env_file:
      - .env
  client:
    depends_on:
      - verbecc
      - api
    container_name: client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 3050:80
    depends_on:
      - client
      - api
      - verbecc
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
