version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - app_network
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
