version: '3'

services:
  verbecc:
    extends:
      file: common-services.yml
      service: verbecc
  api:
    extends:
      file: common-services.yml
      service: api
  client:
    extends:
      file: common-services.yml
      service: client
  nginx:
    extends:
      file: common-services.yml
      service: nginx
    ports:
      - '80:80'
    depends_on:
      - verbecc
      - api
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
