x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}

services:
  verbecc:
    extends:
      file: common-services.yml
      service: verbecc
  api:
    extends:
      file: common-services.yml
      service: api
  client:
    extends:
      file: common-services.yml
      service: client

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
