x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}

services:
  verbecc:
    extends:
      file: common-services.yml
      service: verbecc
  api:
    extends:
      file: common-services.yml
      service: api
      environment:
        - VERBECC_API_URL=verbecc
        - TRPC_PORT=4000
      volumes:
        - ./packages/api:/app/packages/api
        - /app/node_modules
        - /app/dist
        - /app/
    image: ${IMAGE_URI:-api}:${IMAGE_TAG:-latest}
  client:
    extends:
      file: common-services.yml
      service: client
      environment:
        - VERBECC_API=verbecc
        - NODE_ENV=production
        - NEXT_PUBLIC_TRPC_API=api
      volumes:
        - ./:/app
        - /app/node_modules
        - /app/.next
    image: ${IMAGE_URI:-client}:${IMAGE_TAG:-latest}
  nginx:
    extends:
      file: common-services.yml
      service: nginx
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
